// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/ceous.gohtml

package tpl

import (
	generatorModels "github.com/jamillosantos/go-ceous/generator/models"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Ceous generates tpl/ceous.gohtml
func Ceous(ctx *generatorModels.GenContext) string {
	var _b strings.Builder
	RenderCeous(&_b, ctx)
	return _b.String()
}

// RenderCeous render tpl/ceous.gohtml
func RenderCeous(_buffer io.StringWriter, ctx *generatorModels.GenContext) {
	_buffer.WriteString("// Code generated by https://github.com/jamillosantos/go-ceous DO NOT EDIT\n\npackage ")
	_buffer.WriteString(gorazor.HTMLEscape(ctx.OutputPkg.Name))
	_buffer.WriteString("\n\nimport (\n\t\"context\"\n\t\"database/sql\"\n\tceous \"github.com/jamillosantos/go-ceous\"")
	for _, pkg := range ctx.Imports.Imports {
		if pkg.Alias == "-" || pkg.Alias == "ceous" {
			continue
		}

		_buffer.WriteString(("\n"))

		_buffer.WriteString("\t")
		_buffer.WriteString(gorazor.HTMLEscape(pkg.Alias))
		_buffer.WriteString(" \"")
		_buffer.WriteString(gorazor.HTMLEscape(pkg.Pkg.ImportPath))
		_buffer.WriteString("\"")
	}
	_buffer.WriteString("\n)")
	if len(ctx.Connections) > 0 {
		RenderConnections(_buffer, ctx.Connections, ctx.Models)
	}
	RenderTransaction(_buffer, ctx.Models)
	for _, m := range ctx.Models {
		_buffer.WriteString("\n\t")
		RenderResultset(_buffer, m)
		_buffer.WriteString("\n\t")
		RenderQuery(_buffer, ctx, m)
		_buffer.WriteString("\n\t")
		RenderStore(_buffer, ctx, m)
	}

}
