// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/columnValue.gohtml

package tpl

import (
	"github.com/jamillosantos/go-ceous/generator/models"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// ColumnValue generates tpl/columnValue.gohtml
func ColumnValue(model *models.Model) string {
	var _b strings.Builder
	RenderColumnValue(&_b, model)
	return _b.String()
}

// RenderColumnValue render tpl/columnValue.gohtml
func RenderColumnValue(_buffer io.StringWriter, model *models.Model) {
	_buffer.WriteString("\n\nfunc (model ")
	_buffer.WriteString(("*"))
	_buffer.WriteString(gorazor.HTMLEscape(model.Name))
	_buffer.WriteString(") Value(name string) (interface{}, error) {\n\tswitch name {")
	for _, field := range model.Columns {

		_buffer.WriteString(("\n"))

		_buffer.WriteString("\tcase \"")
		_buffer.WriteString(gorazor.HTMLEscape(field.Column))
		_buffer.WriteString("\":\n\t\treturn model.")
		_buffer.WriteString(gorazor.HTMLEscape(field.FullField))
		_buffer.WriteString(", nil")
	}
	_buffer.WriteString("\n\tdefault:\n\t\treturn nil, errors.Wrapf(ceous.ErrFieldNotFound, \"field %s not found\", name)\n\t}\n}")

}
