// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/columnValue.gohtml

package tpl

import (
	. "github.com/jamillosantos/go-ceous/generator/helpers"
	"github.com/jamillosantos/go-ceous/generator/models"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// ColumnValue generates tpl/columnValue.gohtml
func ColumnValue(baseSchema *models.BaseSchema) string {
	var _b strings.Builder
	RenderColumnValue(&_b, baseSchema)
	return _b.String()
}

// RenderColumnValue render tpl/columnValue.gohtml
func RenderColumnValue(_buffer io.StringWriter, baseSchema *models.BaseSchema) {
	_buffer.WriteString("\n\n\n// Value returns the value from a field given its column name.\nfunc (model ")
	_buffer.WriteString(gorazor.HTMLEscape(Pointer))
	_buffer.WriteString(gorazor.HTMLEscape(baseSchema.Name))
	_buffer.WriteString(") Value(name string) (interface{}, error) {\n\tswitch name {")
	for _, field := range baseSchema.Fields {
		_buffer.WriteString("\n\tcase \"")
		_buffer.WriteString(gorazor.HTMLEscape(field.ColumnName))
		_buffer.WriteString("\":\n\t\treturn model.")
		_buffer.WriteString(gorazor.HTMLEscape(field.Name))
		_buffer.WriteString(", nil")
	}
	_buffer.WriteString("\n\tdefault:\n\t\treturn nil, errors.Wrapf(ceous.ErrFieldNotFound, \"field %s not found\", name)\n\t}\n}")

}
