// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/creator.gohtml

package tpl

import (
	. "github.com/jamillosantos/go-ceous/generator/helpers"
	generatorModels "github.com/jamillosantos/go-ceous/generator/models"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Creator generates tpl/creator.gohtml
func Creator(models []*generatorModels.Model) string {
	var _b strings.Builder
	RenderCreator(&_b, models)
	return _b.String()
}

// RenderCreator render tpl/creator.gohtml
func RenderCreator(_buffer io.StringWriter, models []*generatorModels.Model) {
	_buffer.WriteString("\n\ntype Creator struct {")
	for _, model := range models {
		_buffer.WriteString("\n\t")
		_buffer.WriteString(gorazor.HTMLEscape(model.Name))
		_buffer.WriteString("Query(options ...ceous.CeousOption) ")
		_buffer.WriteString(gorazor.HTMLEscape(Pointer))
		_buffer.WriteString(gorazor.HTMLEscape(model.QueryName()))
		_buffer.WriteString("\n\t")
		_buffer.WriteString(gorazor.HTMLEscape(model.Name))
		_buffer.WriteString("Store(options ...ceous.CeousOption) ")
		_buffer.WriteString(gorazor.HTMLEscape(Pointer))
		_buffer.WriteString(gorazor.HTMLEscape(model.QueryName()))
	}
	_buffer.WriteString("\n}")

}
