// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/embedded.gohtml

package tpl

import (
	"github.com/jamillosantos/go-ceous/generator/models"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Embedded generates tpl/embedded.gohtml
func Embedded(model *models.Model) string {
	var _b strings.Builder
	RenderEmbedded(&_b, model)
	return _b.String()
}

// RenderEmbedded render tpl/embedded.gohtml
func RenderEmbedded(_buffer io.StringWriter, model *models.Model) {
	RenderColumnAddress(_buffer, model)
	RenderColumnValue(_buffer, model)
	_buffer.WriteString("\n\ntype schema")
	_buffer.WriteString(gorazor.HTMLEscape(model.Name))
	_buffer.WriteString(" struct {")
	for _, f := range model.Fields {

		_buffer.WriteString(("\n"))

		_buffer.WriteString("\t")
		_buffer.WriteString(gorazor.HTMLEscape(f.Name))
		_buffer.WriteString("  ceous.SchemaField")
	}
	_buffer.WriteString("\n}")

}
