// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/embedded.gohtml

package tpl

import (
	"github.com/jamillosantos/go-ceous/generator/models"
	"io"
	"strings"
)

// Embedded generates tpl/embedded.gohtml
func Embedded(schema *models.Schema) string {
	var _b strings.Builder
	RenderEmbedded(&_b, schema)
	return _b.String()
}

// RenderEmbedded render tpl/embedded.gohtml
func RenderEmbedded(_buffer io.StringWriter, schema *models.Schema) {

}
