// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/model.gohtml

package tpl

import (
	"github.com/jamillosantos/go-ceous/generator/models"
	"io"
	"strings"
)

// Model generates tpl/model.gohtml
func Model(env *models.Environment, model *models.Schema) string {
	var _b strings.Builder
	RenderModel(&_b, env, model)
	return _b.String()
}

// RenderModel render tpl/model.gohtml
func RenderModel(_buffer io.StringWriter, env *models.Environment, model *models.Schema) {

}
