// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/models.gohtml

package tpl

import (
	"github.com/jamillosantos/go-ceous/generator/models"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Models generates tpl/models.gohtml
func Models(env *models.Environment) string {
	var _b strings.Builder
	RenderModels(&_b, env)
	return _b.String()
}

// RenderModels render tpl/models.gohtml
func RenderModels(_buffer io.StringWriter, env *models.Environment) {
	_buffer.WriteString("// Code generated by https://github.com/jamillosantos/go-ceous DO NOT EDIT\n\npackage ")
	_buffer.WriteString(gorazor.HTMLEscape(env.InputPkg.Name))
	_buffer.WriteString("\n\nimport (\n\t\"github.com/jamillosantos/go-ceous\"\n\t\"github.com/pkg/errors\"")
	for _, pkg := range env.ModelsImports.Imports {
		if pkg.Alias == "-" || pkg.Alias == "ceous" || pkg.Alias == "builtin" || pkg.Pkg.ImportPath == "." {
			continue
		}

		_buffer.WriteString(("\n"))

		_buffer.WriteString("\t")
		_buffer.WriteString(gorazor.HTMLEscape(pkg.Alias))
		_buffer.WriteString(" \"")
		_buffer.WriteString(gorazor.HTMLEscape(pkg.Pkg.ImportPath))
		_buffer.WriteString("\"")
	}
	_buffer.WriteString("\n)")
	for _, model := range env.Models {
		RenderModel(_buffer, env, model)
	}

	for _, baseSchema := range env.BaseSchemas {
		RenderColumnValue(_buffer, baseSchema)
		RenderColumnAddress(_buffer, baseSchema)
	}

	RenderSchema(_buffer, env)

}
