// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/models.gohtml

package tpl

import (
	generatorModels "github.com/jamillosantos/go-ceous/generator/models"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Models generates tpl/models.gohtml
func Models(ctx *generatorModels.GenContext) string {
	var _b strings.Builder
	RenderModels(&_b, ctx)
	return _b.String()
}

// RenderModels render tpl/models.gohtml
func RenderModels(_buffer io.StringWriter, ctx *generatorModels.GenContext) {
	_buffer.WriteString("// Code generated by https://github.com/jamillosantos/go-ceous DO NOT EDIT\n\npackage ")
	_buffer.WriteString(gorazor.HTMLEscape(ctx.InputPkg.Name))
	_buffer.WriteString("\n\nimport (\n\t\"github.com/jamillosantos/go-ceous\"\n\t\"github.com/pkg/errors\"")
	for _, pkg := range ctx.ModelsImports.Imports {
		if pkg.Alias == "-" || pkg.Alias == "ceous" || pkg.Pkg.ImportPath == "." {
			continue
		}

		_buffer.WriteString(("\n"))

		_buffer.WriteString("\t")
		_buffer.WriteString(gorazor.HTMLEscape(pkg.Alias))
		_buffer.WriteString(" \"")
		_buffer.WriteString(gorazor.HTMLEscape(pkg.Pkg.ImportPath))
		_buffer.WriteString("\"")
	}
	_buffer.WriteString("\n)")
	for _, m := range ctx.Models {
		RenderModel(_buffer, ctx, m)
	}
	RenderSchema(_buffer, ctx, ctx.Models)

}
