// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/resultset.gohtml

package tpl

import (
	"github.com/jamillosantos/go-ceous/generator/models"
	"io"
	"strings"
)

// Resultset generates tpl/resultset.gohtml
func Resultset(model *models.Schema) string {
	var _b strings.Builder
	RenderResultset(&_b, model)
	return _b.String()
}

// RenderResultset render tpl/resultset.gohtml
func RenderResultset(_buffer io.StringWriter, model *models.Schema) {

}
