// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: tpl/transaction.gohtml

package tpl

import (
	. "github.com/jamillosantos/go-ceous/generator/helpers"
	generatorModels "github.com/jamillosantos/go-ceous/generator/models"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Transaction generates tpl/transaction.gohtml
func Transaction(models []*generatorModels.Model) string {
	var _b strings.Builder
	RenderTransaction(&_b, models)
	return _b.String()
}

// RenderTransaction render tpl/transaction.gohtml
func RenderTransaction(_buffer io.StringWriter, models []*generatorModels.Model) {
	_buffer.WriteString("\n\ntype Transaction struct {\n\t*ceous.BaseTxRunner\n}\n\nfunc NewTransaction(tx *ceous.BaseTxRunner) *Transaction {\n\treturn &Transaction{\n\t\tBaseTxRunner: tx,\n\t}\n}")
	for _, model := range models {
		_buffer.WriteString("\n// ")
		_buffer.WriteString(gorazor.HTMLEscape(model.Name))
		_buffer.WriteString("Query creates a new query from a transaction.\nfunc (c *Transaction) ")
		_buffer.WriteString(gorazor.HTMLEscape(model.Name))
		_buffer.WriteString("Query(options ...ceous.CeousOption) ")
		_buffer.WriteString(gorazor.HTMLEscape(Pointer))
		_buffer.WriteString(gorazor.HTMLEscape(model.QueryName()))
		_buffer.WriteString(" {\n\treturn New")
		_buffer.WriteString(gorazor.HTMLEscape(model.Name))
		_buffer.WriteString("Query(append(options, ceous.WithRunner(c))...)\n}\n\n// ")
		_buffer.WriteString(gorazor.HTMLEscape(model.Name))
		_buffer.WriteString("Store creates a new store from a transaction.\nfunc (c *Transaction) ")
		_buffer.WriteString(gorazor.HTMLEscape(model.Name))
		_buffer.WriteString("Store(options ...ceous.CeousOption) ")
		_buffer.WriteString(gorazor.HTMLEscape(Pointer))
		_buffer.WriteString(gorazor.HTMLEscape(model.StoreName()))
		_buffer.WriteString(" {\n\treturn New")
		_buffer.WriteString(gorazor.HTMLEscape(model.Name))
		_buffer.WriteString("Store(append(options, ceous.WithRunner(c))...)\n}")
	}

}
