name: Go
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install gobin
        run: GOBIN=$GOROOT/bin GO111MODULE=off go get -u github.com/myitcv/gobin

      - name: Install tools
        run: gobin github.com/gordonklaus/ineffassign github.com/fzipp/gocyclo github.com/client9/misspell/cmd/misspell

      - name: go fmt
        run: test -z $(go fmt ./...)

      - name: go vet
        run: go vet ./...

      - name: gocyclo
        run: /home/runner/go/bin/gocyclo -over 25 ./

      - name: ineffassign
        run: /home/runner/go/bin/ineffassign ./

      - name: misspell
        run: /home/runner/go/bin/misspell ./

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go run github.com/onsi/ginkgo/ginkgo -r --randomizeAllSpecs --randomizeSuites --cover --trace --race --compilers=2 -coverprofile=coverage.txt -covermode=atomic

      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
